services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 10mb --maxmemory-policy noeviction
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}

  telegram-table-status-bot:
    build:
      context: ./
    depends_on:
      - redis
    volumes:
      - data:/data
    restart: on-failure:10
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - GSA_FILE=${GSA_FILE}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}

volumes:
  data:
  redis_data: